autoInstallPeers: true

strictPeerDependencies: false

forceLegacyDeploy: true

packages:
  - apps/*
  - packages/*
  - tests/*

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - 'esbuild'
