name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: lts/*
          args: --ignore-scripts
      - name: Run Biome
        run: pnpm biome ci
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: alford92
          POSTGRES_PASSWORD: mollit-non-dolor-laboris
          POSTGRES_DB: gullible-transparency
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      integresql:
        image: allaboutapps/integresql
        env:
          PGUSER: alford92
          PGPASSWORD: mollit-non-dolor-laboris
          PGDATABASE: gullible-transparency
          PGHOST: postgres
          PGPORT: "5432"
          PGSSLMODE: disable
        ports:
          - 5000:5000
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: lts/*
          args: --frozen-lockfile
      - name: Install golang-migrate/migrate
        run: |
          cd $(mktemp -d)
          curl -L https://github.com/golang-migrate/migrate/releases/download/$version/migrate.linux-amd64.tar.gz | tar xvz
          mv migrate /usr/local/bin/migrate
      - name: Run tests
        run: pnpm test
        env:
          POSTGRES_USER: alford92
          POSTGRES_PASSWORD: mollit-non-dolor-laboris
          POSTGRES_DB: gullible-transparency
          POSTGRES_HOST: localhost
          INTEGRESQL_URL: http://localhost:5000
